name: Release Images

on:
  schedule:
    - cron: '0 8 * * *' # everyday at 8am UTC
  release:
    types: [ published ]
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  registry:
    name: Build & Push
    uses: XNXKTech/workflows/.github/workflows/docker-build.yml@main
    with:
      runs-on: "['self-hosted']"
      registry: 'xnxktech.tencentcloudcr.com'
      build-args: |
        CI=true
        X_ENV=production
    secrets:
      USERNAME: ${{ secrets.REGISTRY_USER }}
      PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
